version: '3.7'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'
    volumes:
      - ./src:/app/src
      - /app/node_modules
    stdin_open: true
    restart: always
    env_file:
      - .env
